FROM ghcr.io/nationalarchives/tna-python-dev:latest AS build
COPY . .
RUN tna-build
RUN mkdir -p site/fmt site/x-fmt site/actor site/edit/fmt site/edit/x-fmt site/actor/edit
RUN cp styles/main.css node_modules/@nationalarchives/frontend/nationalarchives/all.css node_modules/@nationalarchives/frontend/nationalarchives/all.css.map node_modules/@nationalarchives/frontend/nationalarchives/all.js node_modules/@nationalarchives/frontend/nationalarchives/all.js.map node_modules/@nationalarchives/frontend/nationalarchives/font-awesome.css node_modules/@nationalarchives/frontend/nationalarchives/font-awesome.css.map node_modules/@nationalarchives/frontend/nationalarchives/ie.css node_modules/@nationalarchives/frontend/nationalarchives/ie.css.map node_modules/@nationalarchives/frontend/nationalarchives/print.css node_modules/@nationalarchives/frontend/nationalarchives/print.css.map node_modules/@nationalarchives/frontend/nationalarchives/assets/images/favicon.ico node_modules/@nationalarchives/frontend/nationalarchives/assets/fonts/fa-solid-900.woff2 site
RUN sed -i -e 's/\/assets\/fonts/\//g' site/font-awesome.css
RUN cp lambdas/templates/site.js site
RUN git clone https://github.com/nationalarchives/pronom-signatures/ /home/app/pronom-signatures
RUN poetry run python .github/scripts/generate_pages.py /home/app/pronom-signatures



FROM nginx:latest
COPY --from=build /app/site /usr/share/nginx/html