FROM ghcr.io/nationalarchives/tna-python-dev
HEALTHCHECK --interval=15s CMD curl --fail http://localhost:8080/healthcheck/live/ || exit 1
COPY pyproject.toml poetry.lock package.json package-lock.json ./
RUN tna-build
RUN git clone https://github.com/nationalarchives/pronom-signatures/ /home/app/pronom-signatures
COPY . .
RUN poetry run python .github/scripts/generate_index_file.py /home/app/pronom-signatures
CMD ["tna-run", "app:app"]
