services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - ./:/app
    restart: unless-stopped
