name: Test

on:
  push:
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - run: |
          (cd terraform && terraform fmt -check --recursive)
          docker compose up --detach --wait --wait-timeout 120
          docker compose exec app poetry run python .github/scripts/generate_index_file.py /home/app/pronom-signatures
          npm --prefix tests cit
          docker compose exec app poetry run python -m unittest discover -v -s lambdas/test
