name: Test

on:
  push:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test changed files
    steps:
      - name: Provision runner
        uses: nationalarchives/org-actions-provision-runner@5657f48ecd0fd31bfe857919149f1fdc690d53ed # v1.0.1
        with:
          wiz-sensor-token: ${{ secrets.WIZ_SENSOR_TOKEN }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - run: |
          (cd terraform && terraform fmt -check --recursive)
          docker compose up --detach --wait --wait-timeout 120
          docker compose exec app poetry run python .github/scripts/generate_index_file.py /home/app/pronom-signatures
          cd tests
          npm --ignore-scripts ci
          npx cypress install
          npx cypress run
          cd ..
          docker compose exec app poetry run python -m unittest discover -v -s lambdas/test
        env:
          GITHUB_TOKEN: ${{ github.token }}

  check-formatting:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - name: Provision runner
        uses: nationalarchives/org-actions-provision-runner@5657f48ecd0fd31bfe857919149f1fdc690d53ed # v1.0.1
        with:
          wiz-sensor-token: ${{ secrets.WIZ_SENSOR_TOKEN }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
      - run: docker run --rm -v "$(pwd)":/app/ ghcr.io/nationalarchives/tna-python-dev:preview checkformat
